# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6004119c195a663c1b7e617a1d0c56346f93a551b11adf6be2bdd78917c9744869d47902f85650cee057992aad40f835f4721bda37debafe3669f997d7b9eb5

test:
  secret_key_base: 059a1de259c100ca7dadf10b380b5c42cfae434bcf32a8f696348bef5a32f0a59b52d813ccf3f6c208ca1e6bfd2744c3b5263a70d6422bdd59c8ed2d92ab26d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
